aliases:
    - &restore_gradle_cache
        name: Restore Gradle cache
        key: gradle-{{ .Branch }}

    - &save_gradle_cache
        name: Save Gradle cache
        key: gradle-{{ .Branch }}
        paths:
            - ~/.gradle

    - &download_dependencies
        name: Download Dependencies
        command: ./gradlew androidDependencies



    - &ktlint
        name: Run Ktlint
        command: ./gradlew ktlintCheck

    - &detekt
        name: Run Detekt
        command: ./gradlew detekt

    - &lint
        name: Run Lint
        command: ./gradlew lint

    - &unit_tests
        name: Run Unit Tests
        command: ./gradlew testDebugUnitTest

jobs:
    setup_environment:
        working_directory: ~/data
        docker:
            - image: circleci/android:api-28
        environment:
            JVM_OPTS: -Xmx4g
            - checkout
            - restore_cache: *restore_gradle_cache
            - run: *download_dependencies
            - save_cache: *save_gradle_cache

    ktlint:
        docker:
            - image: circleci/android:api-28
        steps:
            - checkout
            - run: ./gradlew ktlintCheck
    detekt:
        docker:
            - image: circleci/android:api-28
        steps:
            - run: ./gradlew detekt

workflows:
    version: 2
    build_and_check:
        jobs:
            - ktlint
                requires:
                    - setup_environment
            - detekt
                requires:
                    - setup_environment

