jobs:
    prepare_project:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run:
                  name: Download Dependencies
                  command: ./gradlew androidDependencies
            - save_cache:
                  paths:
                      - ~/.gradle
                  key: gradle-{{ .Branch }}

    ktlint:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - run: ./gradlew ktlintCheck
    detekt:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - run: ./gradlew detekt

workflows:
    version: 2
    build_and_check:
        jobs:
            - ktlint
                requires:
                    - prepare_project
            - detekt
                requires:
                    - prepare_project

