version: 2.1

jobs:
    ktlint:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - checkout
            - run: ./gradlew ktlintCheck
    detekt:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - checkout
            - run: ./gradlew detekt

workflows:
    version: 2
    build_and_check:
        jobs:
            - ktlint
            - detekt
