jobs:
    setup_environment:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g
                -
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run: ./gradlew androidDependencies
                       - save_cache:
                       key: gradle-{{ .Branch }}
                       paths:
                           - ~/.gradle

    ktlint:
        docker:
            - image: circleci/android:api-28
        steps:
            - run: ./gradlew ktlintCheck
    detekt:
        docker:
            - image: circleci/android:api-28
        steps:
            - run: ./gradlew detekt

workflows:
    version: 2
    build_and_check:
        jobs:
            - ktlint
                requires:
                    - setup_environment
            - detekt
                requires:
                    - setup_environment

