version: 2.1

jobs:
    build:
        working_directory: ~/code
        docker:
            - image: circleci/android:api-28
        environment:
            JVM_OPTS: -Xmx4g
        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ checksum "build.gradle.kts" }}-{{ checksum  "buildSrc/src/main/kotlin/AndroidConfig.kt" }}-{{ checksum  "buildSrc/src/main/kotlin/CoreVersion.kt" }}-{{ checksum  "buildSrc/src/main/kotlin/LibraryDependency.kt" }}-{{ checksum  "buildSrc/src/main/kotlin/TestLibraryDependency.kt" }}-{{ checksum  "buildSrc/src/main/kotlin/GradleDependency.kt" }}-{{ checksum  "gradle/wrapper/gradle-wrapper.properties" }}
            - run:
                  name: Download Dependencies
                  command: ./gradlew androidDependencies
            - save_cache:
                  paths:
                      - ~/.gradle
                  key: gradle-{{ checksum "build.gradle.kts" }}-{{ checksum  "buildSrc/src/main/kotlin/AndroidConfig.kt" }}-{{ checksum  "buildSrc/src/main/kotlin/CoreVersion.kt" }}-{{ checksum  "buildSrc/src/main/kotlin/LibraryDependency.kt" }}-{{ checksum  "buildSrc/src/main/kotlin/TestLibraryDependency.kt" }}-{{ checksum  "buildSrc/src/main/kotlin/GradleDependency.kt" }}-{{ checksum  "gradle/wrapper/gradle-wrapper.properties" }}
            - run:
                  name: Run Ktlint
                  command: ./gradlew ktlintCheck
            - run:
                  name: Run Detekt
                  command: ./gradlew detekt
            - run:
                  name: Run Lint
                  command: ./gradlew lint
            - run:
                  name: Run Tests
                  command: ./gradlew testDebugUnitTest
            - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
                  path: app/build/reports
                  destination: reports
            - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
                  path: app/build/test-results
            # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
