version: 2.1

jobs:
    ktlint:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run:
                  name: Download Dependencies
                  command: ./gradlew androidDependencies
            - save_cache:
                  paths:
                      - ~/.gradle
                  key: gradle-{{ .Branch }}
            - run: ./gradlew ktlintCheck
    detekt:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run:
                  name: Download Dependencies
                  command: ./gradlew androidDependencies
            - save_cache:
                  paths:
                      - ~/.gradle
                  key: gradle-{{ .Branch }}
            - run: ./gradlew detekt

    lint:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run:
                  name: Download Dependencies
                  command: ./gradlew androidDependencies
            - save_cache:
                  paths:
                      - ~/.gradle
                  key: gradle-{{ .Branch }}
            - run: ./gradlew lint

    test:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run:
                  name: Download Dependencies
                  command: ./gradlew androidDependencies
            - save_cache:
                  paths:
                      - ~/.gradle
                  key: gradle-{{ .Branch }}
            - run: ./gradlew testDebugUnitTest

    build:
        working_directory: ~/data

        docker:
            - image: circleci/android:api-28

        environment:
            JVM_OPTS: -Xmx4g

        steps:
            - checkout
            - restore_cache:
                  key: gradle-{{ .Branch }}
            - run:
                  name: Download Dependencies
                  command: ./gradlew androidDependencies
            - save_cache:
                  paths:
                      - ~/.gradle
                  key: gradle-{{ .Branch }}
            - run: ./gradlew :app:bundleDebug
workflows:
    version: 2
    build_and_check:
        jobs:
            - lint
            - detekt
            - ktlint
            - test
            - build:
                requires:
                    - lint
                    - detekt
                    - ktlint
                    - test
